// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {Test} from "forge-std/Test.sol";
import {Config} from "../src/Config.sol";
import {ChipToken} from "../src/ChipToken.sol";
import {SpiritCards} from "../src/SpiritCards.sol";
import {Packs} from "../src/Packs.sol";

/// @title EdgeCasesTest — systematically enumerated, deterministic edge cases.
/// @notice Includes exhaustive per-bit verification of SpiritCards.leadingZeroBits
///         (bit positions 0..255 plus the all-zero/all-one boundaries), the staking
///         tier table, the pack size/discount table, and pack price math.
///         Generated by tools; do not hand-edit individual cases.
contract EdgeCasesTest is Test {
    Config config;
    ChipToken chip;
    SpiritCards poc;
    Packs packs;

    uint256 constant ERA_PRICE = 0.001 ether;

    function setUp() public {
        vm.warp(1_000_000);
        config = new Config();
        config.setMining(8, 0, 1_000_000, 3600);
        config.setPricing(ERA_PRICE, 2500, 1000);
        config.setSplit(6000, 1000, 3000, 0);
        chip = new ChipToken();
        poc = new SpiritCards(config, chip, "https://example.invalid/poc/");
        chip.setMinter(address(poc));
        packs = new Packs(config, poc);
        poc.setPackMinter(address(packs));
    }

    // ==============================================================
    // leadingZeroBits: bit `b` set => exactly `b` leading zero bits
    // ==============================================================
    function test_LeadingZeroBits_bit0() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 255)), 0, "bit 0");
    }

    function test_LeadingZeroBits_bit1() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 254)), 1, "bit 1");
    }

    function test_LeadingZeroBits_bit2() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 253)), 2, "bit 2");
    }

    function test_LeadingZeroBits_bit3() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 252)), 3, "bit 3");
    }

    function test_LeadingZeroBits_bit4() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 251)), 4, "bit 4");
    }

    function test_LeadingZeroBits_bit5() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 250)), 5, "bit 5");
    }

    function test_LeadingZeroBits_bit6() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 249)), 6, "bit 6");
    }

    function test_LeadingZeroBits_bit7() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 248)), 7, "bit 7");
    }

    function test_LeadingZeroBits_bit8() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 247)), 8, "bit 8");
    }

    function test_LeadingZeroBits_bit9() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 246)), 9, "bit 9");
    }

    function test_LeadingZeroBits_bit10() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 245)), 10, "bit 10");
    }

    function test_LeadingZeroBits_bit11() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 244)), 11, "bit 11");
    }

    function test_LeadingZeroBits_bit12() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 243)), 12, "bit 12");
    }

    function test_LeadingZeroBits_bit13() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 242)), 13, "bit 13");
    }

    function test_LeadingZeroBits_bit14() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 241)), 14, "bit 14");
    }

    function test_LeadingZeroBits_bit15() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 240)), 15, "bit 15");
    }

    function test_LeadingZeroBits_bit16() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 239)), 16, "bit 16");
    }

    function test_LeadingZeroBits_bit17() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 238)), 17, "bit 17");
    }

    function test_LeadingZeroBits_bit18() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 237)), 18, "bit 18");
    }

    function test_LeadingZeroBits_bit19() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 236)), 19, "bit 19");
    }

    function test_LeadingZeroBits_bit20() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 235)), 20, "bit 20");
    }

    function test_LeadingZeroBits_bit21() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 234)), 21, "bit 21");
    }

    function test_LeadingZeroBits_bit22() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 233)), 22, "bit 22");
    }

    function test_LeadingZeroBits_bit23() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 232)), 23, "bit 23");
    }

    function test_LeadingZeroBits_bit24() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 231)), 24, "bit 24");
    }

    function test_LeadingZeroBits_bit25() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 230)), 25, "bit 25");
    }

    function test_LeadingZeroBits_bit26() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 229)), 26, "bit 26");
    }

    function test_LeadingZeroBits_bit27() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 228)), 27, "bit 27");
    }

    function test_LeadingZeroBits_bit28() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 227)), 28, "bit 28");
    }

    function test_LeadingZeroBits_bit29() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 226)), 29, "bit 29");
    }

    function test_LeadingZeroBits_bit30() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 225)), 30, "bit 30");
    }

    function test_LeadingZeroBits_bit31() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 224)), 31, "bit 31");
    }

    function test_LeadingZeroBits_bit32() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 223)), 32, "bit 32");
    }

    function test_LeadingZeroBits_bit33() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 222)), 33, "bit 33");
    }

    function test_LeadingZeroBits_bit34() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 221)), 34, "bit 34");
    }

    function test_LeadingZeroBits_bit35() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 220)), 35, "bit 35");
    }

    function test_LeadingZeroBits_bit36() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 219)), 36, "bit 36");
    }

    function test_LeadingZeroBits_bit37() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 218)), 37, "bit 37");
    }

    function test_LeadingZeroBits_bit38() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 217)), 38, "bit 38");
    }

    function test_LeadingZeroBits_bit39() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 216)), 39, "bit 39");
    }

    function test_LeadingZeroBits_bit40() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 215)), 40, "bit 40");
    }

    function test_LeadingZeroBits_bit41() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 214)), 41, "bit 41");
    }

    function test_LeadingZeroBits_bit42() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 213)), 42, "bit 42");
    }

    function test_LeadingZeroBits_bit43() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 212)), 43, "bit 43");
    }

    function test_LeadingZeroBits_bit44() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 211)), 44, "bit 44");
    }

    function test_LeadingZeroBits_bit45() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 210)), 45, "bit 45");
    }

    function test_LeadingZeroBits_bit46() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 209)), 46, "bit 46");
    }

    function test_LeadingZeroBits_bit47() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 208)), 47, "bit 47");
    }

    function test_LeadingZeroBits_bit48() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 207)), 48, "bit 48");
    }

    function test_LeadingZeroBits_bit49() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 206)), 49, "bit 49");
    }

    function test_LeadingZeroBits_bit50() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 205)), 50, "bit 50");
    }

    function test_LeadingZeroBits_bit51() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 204)), 51, "bit 51");
    }

    function test_LeadingZeroBits_bit52() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 203)), 52, "bit 52");
    }

    function test_LeadingZeroBits_bit53() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 202)), 53, "bit 53");
    }

    function test_LeadingZeroBits_bit54() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 201)), 54, "bit 54");
    }

    function test_LeadingZeroBits_bit55() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 200)), 55, "bit 55");
    }

    function test_LeadingZeroBits_bit56() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 199)), 56, "bit 56");
    }

    function test_LeadingZeroBits_bit57() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 198)), 57, "bit 57");
    }

    function test_LeadingZeroBits_bit58() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 197)), 58, "bit 58");
    }

    function test_LeadingZeroBits_bit59() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 196)), 59, "bit 59");
    }

    function test_LeadingZeroBits_bit60() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 195)), 60, "bit 60");
    }

    function test_LeadingZeroBits_bit61() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 194)), 61, "bit 61");
    }

    function test_LeadingZeroBits_bit62() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 193)), 62, "bit 62");
    }

    function test_LeadingZeroBits_bit63() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 192)), 63, "bit 63");
    }

    function test_LeadingZeroBits_bit64() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 191)), 64, "bit 64");
    }

    function test_LeadingZeroBits_bit65() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 190)), 65, "bit 65");
    }

    function test_LeadingZeroBits_bit66() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 189)), 66, "bit 66");
    }

    function test_LeadingZeroBits_bit67() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 188)), 67, "bit 67");
    }

    function test_LeadingZeroBits_bit68() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 187)), 68, "bit 68");
    }

    function test_LeadingZeroBits_bit69() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 186)), 69, "bit 69");
    }

    function test_LeadingZeroBits_bit70() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 185)), 70, "bit 70");
    }

    function test_LeadingZeroBits_bit71() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 184)), 71, "bit 71");
    }

    function test_LeadingZeroBits_bit72() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 183)), 72, "bit 72");
    }

    function test_LeadingZeroBits_bit73() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 182)), 73, "bit 73");
    }

    function test_LeadingZeroBits_bit74() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 181)), 74, "bit 74");
    }

    function test_LeadingZeroBits_bit75() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 180)), 75, "bit 75");
    }

    function test_LeadingZeroBits_bit76() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 179)), 76, "bit 76");
    }

    function test_LeadingZeroBits_bit77() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 178)), 77, "bit 77");
    }

    function test_LeadingZeroBits_bit78() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 177)), 78, "bit 78");
    }

    function test_LeadingZeroBits_bit79() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 176)), 79, "bit 79");
    }

    function test_LeadingZeroBits_bit80() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 175)), 80, "bit 80");
    }

    function test_LeadingZeroBits_bit81() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 174)), 81, "bit 81");
    }

    function test_LeadingZeroBits_bit82() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 173)), 82, "bit 82");
    }

    function test_LeadingZeroBits_bit83() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 172)), 83, "bit 83");
    }

    function test_LeadingZeroBits_bit84() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 171)), 84, "bit 84");
    }

    function test_LeadingZeroBits_bit85() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 170)), 85, "bit 85");
    }

    function test_LeadingZeroBits_bit86() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 169)), 86, "bit 86");
    }

    function test_LeadingZeroBits_bit87() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 168)), 87, "bit 87");
    }

    function test_LeadingZeroBits_bit88() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 167)), 88, "bit 88");
    }

    function test_LeadingZeroBits_bit89() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 166)), 89, "bit 89");
    }

    function test_LeadingZeroBits_bit90() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 165)), 90, "bit 90");
    }

    function test_LeadingZeroBits_bit91() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 164)), 91, "bit 91");
    }

    function test_LeadingZeroBits_bit92() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 163)), 92, "bit 92");
    }

    function test_LeadingZeroBits_bit93() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 162)), 93, "bit 93");
    }

    function test_LeadingZeroBits_bit94() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 161)), 94, "bit 94");
    }

    function test_LeadingZeroBits_bit95() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 160)), 95, "bit 95");
    }

    function test_LeadingZeroBits_bit96() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 159)), 96, "bit 96");
    }

    function test_LeadingZeroBits_bit97() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 158)), 97, "bit 97");
    }

    function test_LeadingZeroBits_bit98() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 157)), 98, "bit 98");
    }

    function test_LeadingZeroBits_bit99() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 156)), 99, "bit 99");
    }

    function test_LeadingZeroBits_bit100() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 155)), 100, "bit 100");
    }

    function test_LeadingZeroBits_bit101() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 154)), 101, "bit 101");
    }

    function test_LeadingZeroBits_bit102() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 153)), 102, "bit 102");
    }

    function test_LeadingZeroBits_bit103() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 152)), 103, "bit 103");
    }

    function test_LeadingZeroBits_bit104() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 151)), 104, "bit 104");
    }

    function test_LeadingZeroBits_bit105() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 150)), 105, "bit 105");
    }

    function test_LeadingZeroBits_bit106() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 149)), 106, "bit 106");
    }

    function test_LeadingZeroBits_bit107() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 148)), 107, "bit 107");
    }

    function test_LeadingZeroBits_bit108() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 147)), 108, "bit 108");
    }

    function test_LeadingZeroBits_bit109() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 146)), 109, "bit 109");
    }

    function test_LeadingZeroBits_bit110() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 145)), 110, "bit 110");
    }

    function test_LeadingZeroBits_bit111() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 144)), 111, "bit 111");
    }

    function test_LeadingZeroBits_bit112() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 143)), 112, "bit 112");
    }

    function test_LeadingZeroBits_bit113() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 142)), 113, "bit 113");
    }

    function test_LeadingZeroBits_bit114() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 141)), 114, "bit 114");
    }

    function test_LeadingZeroBits_bit115() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 140)), 115, "bit 115");
    }

    function test_LeadingZeroBits_bit116() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 139)), 116, "bit 116");
    }

    function test_LeadingZeroBits_bit117() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 138)), 117, "bit 117");
    }

    function test_LeadingZeroBits_bit118() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 137)), 118, "bit 118");
    }

    function test_LeadingZeroBits_bit119() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 136)), 119, "bit 119");
    }

    function test_LeadingZeroBits_bit120() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 135)), 120, "bit 120");
    }

    function test_LeadingZeroBits_bit121() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 134)), 121, "bit 121");
    }

    function test_LeadingZeroBits_bit122() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 133)), 122, "bit 122");
    }

    function test_LeadingZeroBits_bit123() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 132)), 123, "bit 123");
    }

    function test_LeadingZeroBits_bit124() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 131)), 124, "bit 124");
    }

    function test_LeadingZeroBits_bit125() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 130)), 125, "bit 125");
    }

    function test_LeadingZeroBits_bit126() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 129)), 126, "bit 126");
    }

    function test_LeadingZeroBits_bit127() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 128)), 127, "bit 127");
    }

    function test_LeadingZeroBits_bit128() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 127)), 128, "bit 128");
    }

    function test_LeadingZeroBits_bit129() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 126)), 129, "bit 129");
    }

    function test_LeadingZeroBits_bit130() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 125)), 130, "bit 130");
    }

    function test_LeadingZeroBits_bit131() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 124)), 131, "bit 131");
    }

    function test_LeadingZeroBits_bit132() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 123)), 132, "bit 132");
    }

    function test_LeadingZeroBits_bit133() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 122)), 133, "bit 133");
    }

    function test_LeadingZeroBits_bit134() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 121)), 134, "bit 134");
    }

    function test_LeadingZeroBits_bit135() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 120)), 135, "bit 135");
    }

    function test_LeadingZeroBits_bit136() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 119)), 136, "bit 136");
    }

    function test_LeadingZeroBits_bit137() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 118)), 137, "bit 137");
    }

    function test_LeadingZeroBits_bit138() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 117)), 138, "bit 138");
    }

    function test_LeadingZeroBits_bit139() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 116)), 139, "bit 139");
    }

    function test_LeadingZeroBits_bit140() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 115)), 140, "bit 140");
    }

    function test_LeadingZeroBits_bit141() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 114)), 141, "bit 141");
    }

    function test_LeadingZeroBits_bit142() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 113)), 142, "bit 142");
    }

    function test_LeadingZeroBits_bit143() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 112)), 143, "bit 143");
    }

    function test_LeadingZeroBits_bit144() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 111)), 144, "bit 144");
    }

    function test_LeadingZeroBits_bit145() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 110)), 145, "bit 145");
    }

    function test_LeadingZeroBits_bit146() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 109)), 146, "bit 146");
    }

    function test_LeadingZeroBits_bit147() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 108)), 147, "bit 147");
    }

    function test_LeadingZeroBits_bit148() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 107)), 148, "bit 148");
    }

    function test_LeadingZeroBits_bit149() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 106)), 149, "bit 149");
    }

    function test_LeadingZeroBits_bit150() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 105)), 150, "bit 150");
    }

    function test_LeadingZeroBits_bit151() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 104)), 151, "bit 151");
    }

    function test_LeadingZeroBits_bit152() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 103)), 152, "bit 152");
    }

    function test_LeadingZeroBits_bit153() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 102)), 153, "bit 153");
    }

    function test_LeadingZeroBits_bit154() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 101)), 154, "bit 154");
    }

    function test_LeadingZeroBits_bit155() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 100)), 155, "bit 155");
    }

    function test_LeadingZeroBits_bit156() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 99)), 156, "bit 156");
    }

    function test_LeadingZeroBits_bit157() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 98)), 157, "bit 157");
    }

    function test_LeadingZeroBits_bit158() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 97)), 158, "bit 158");
    }

    function test_LeadingZeroBits_bit159() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 96)), 159, "bit 159");
    }

    function test_LeadingZeroBits_bit160() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 95)), 160, "bit 160");
    }

    function test_LeadingZeroBits_bit161() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 94)), 161, "bit 161");
    }

    function test_LeadingZeroBits_bit162() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 93)), 162, "bit 162");
    }

    function test_LeadingZeroBits_bit163() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 92)), 163, "bit 163");
    }

    function test_LeadingZeroBits_bit164() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 91)), 164, "bit 164");
    }

    function test_LeadingZeroBits_bit165() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 90)), 165, "bit 165");
    }

    function test_LeadingZeroBits_bit166() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 89)), 166, "bit 166");
    }

    function test_LeadingZeroBits_bit167() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 88)), 167, "bit 167");
    }

    function test_LeadingZeroBits_bit168() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 87)), 168, "bit 168");
    }

    function test_LeadingZeroBits_bit169() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 86)), 169, "bit 169");
    }

    function test_LeadingZeroBits_bit170() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 85)), 170, "bit 170");
    }

    function test_LeadingZeroBits_bit171() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 84)), 171, "bit 171");
    }

    function test_LeadingZeroBits_bit172() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 83)), 172, "bit 172");
    }

    function test_LeadingZeroBits_bit173() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 82)), 173, "bit 173");
    }

    function test_LeadingZeroBits_bit174() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 81)), 174, "bit 174");
    }

    function test_LeadingZeroBits_bit175() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 80)), 175, "bit 175");
    }

    function test_LeadingZeroBits_bit176() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 79)), 176, "bit 176");
    }

    function test_LeadingZeroBits_bit177() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 78)), 177, "bit 177");
    }

    function test_LeadingZeroBits_bit178() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 77)), 178, "bit 178");
    }

    function test_LeadingZeroBits_bit179() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 76)), 179, "bit 179");
    }

    function test_LeadingZeroBits_bit180() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 75)), 180, "bit 180");
    }

    function test_LeadingZeroBits_bit181() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 74)), 181, "bit 181");
    }

    function test_LeadingZeroBits_bit182() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 73)), 182, "bit 182");
    }

    function test_LeadingZeroBits_bit183() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 72)), 183, "bit 183");
    }

    function test_LeadingZeroBits_bit184() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 71)), 184, "bit 184");
    }

    function test_LeadingZeroBits_bit185() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 70)), 185, "bit 185");
    }

    function test_LeadingZeroBits_bit186() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 69)), 186, "bit 186");
    }

    function test_LeadingZeroBits_bit187() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 68)), 187, "bit 187");
    }

    function test_LeadingZeroBits_bit188() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 67)), 188, "bit 188");
    }

    function test_LeadingZeroBits_bit189() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 66)), 189, "bit 189");
    }

    function test_LeadingZeroBits_bit190() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 65)), 190, "bit 190");
    }

    function test_LeadingZeroBits_bit191() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 64)), 191, "bit 191");
    }

    function test_LeadingZeroBits_bit192() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 63)), 192, "bit 192");
    }

    function test_LeadingZeroBits_bit193() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 62)), 193, "bit 193");
    }

    function test_LeadingZeroBits_bit194() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 61)), 194, "bit 194");
    }

    function test_LeadingZeroBits_bit195() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 60)), 195, "bit 195");
    }

    function test_LeadingZeroBits_bit196() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 59)), 196, "bit 196");
    }

    function test_LeadingZeroBits_bit197() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 58)), 197, "bit 197");
    }

    function test_LeadingZeroBits_bit198() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 57)), 198, "bit 198");
    }

    function test_LeadingZeroBits_bit199() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 56)), 199, "bit 199");
    }

    function test_LeadingZeroBits_bit200() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 55)), 200, "bit 200");
    }

    function test_LeadingZeroBits_bit201() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 54)), 201, "bit 201");
    }

    function test_LeadingZeroBits_bit202() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 53)), 202, "bit 202");
    }

    function test_LeadingZeroBits_bit203() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 52)), 203, "bit 203");
    }

    function test_LeadingZeroBits_bit204() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 51)), 204, "bit 204");
    }

    function test_LeadingZeroBits_bit205() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 50)), 205, "bit 205");
    }

    function test_LeadingZeroBits_bit206() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 49)), 206, "bit 206");
    }

    function test_LeadingZeroBits_bit207() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 48)), 207, "bit 207");
    }

    function test_LeadingZeroBits_bit208() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 47)), 208, "bit 208");
    }

    function test_LeadingZeroBits_bit209() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 46)), 209, "bit 209");
    }

    function test_LeadingZeroBits_bit210() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 45)), 210, "bit 210");
    }

    function test_LeadingZeroBits_bit211() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 44)), 211, "bit 211");
    }

    function test_LeadingZeroBits_bit212() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 43)), 212, "bit 212");
    }

    function test_LeadingZeroBits_bit213() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 42)), 213, "bit 213");
    }

    function test_LeadingZeroBits_bit214() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 41)), 214, "bit 214");
    }

    function test_LeadingZeroBits_bit215() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 40)), 215, "bit 215");
    }

    function test_LeadingZeroBits_bit216() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 39)), 216, "bit 216");
    }

    function test_LeadingZeroBits_bit217() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 38)), 217, "bit 217");
    }

    function test_LeadingZeroBits_bit218() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 37)), 218, "bit 218");
    }

    function test_LeadingZeroBits_bit219() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 36)), 219, "bit 219");
    }

    function test_LeadingZeroBits_bit220() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 35)), 220, "bit 220");
    }

    function test_LeadingZeroBits_bit221() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 34)), 221, "bit 221");
    }

    function test_LeadingZeroBits_bit222() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 33)), 222, "bit 222");
    }

    function test_LeadingZeroBits_bit223() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 32)), 223, "bit 223");
    }

    function test_LeadingZeroBits_bit224() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 31)), 224, "bit 224");
    }

    function test_LeadingZeroBits_bit225() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 30)), 225, "bit 225");
    }

    function test_LeadingZeroBits_bit226() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 29)), 226, "bit 226");
    }

    function test_LeadingZeroBits_bit227() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 28)), 227, "bit 227");
    }

    function test_LeadingZeroBits_bit228() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 27)), 228, "bit 228");
    }

    function test_LeadingZeroBits_bit229() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 26)), 229, "bit 229");
    }

    function test_LeadingZeroBits_bit230() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 25)), 230, "bit 230");
    }

    function test_LeadingZeroBits_bit231() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 24)), 231, "bit 231");
    }

    function test_LeadingZeroBits_bit232() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 23)), 232, "bit 232");
    }

    function test_LeadingZeroBits_bit233() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 22)), 233, "bit 233");
    }

    function test_LeadingZeroBits_bit234() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 21)), 234, "bit 234");
    }

    function test_LeadingZeroBits_bit235() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 20)), 235, "bit 235");
    }

    function test_LeadingZeroBits_bit236() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 19)), 236, "bit 236");
    }

    function test_LeadingZeroBits_bit237() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 18)), 237, "bit 237");
    }

    function test_LeadingZeroBits_bit238() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 17)), 238, "bit 238");
    }

    function test_LeadingZeroBits_bit239() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 16)), 239, "bit 239");
    }

    function test_LeadingZeroBits_bit240() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 15)), 240, "bit 240");
    }

    function test_LeadingZeroBits_bit241() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 14)), 241, "bit 241");
    }

    function test_LeadingZeroBits_bit242() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 13)), 242, "bit 242");
    }

    function test_LeadingZeroBits_bit243() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 12)), 243, "bit 243");
    }

    function test_LeadingZeroBits_bit244() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 11)), 244, "bit 244");
    }

    function test_LeadingZeroBits_bit245() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 10)), 245, "bit 245");
    }

    function test_LeadingZeroBits_bit246() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 9)), 246, "bit 246");
    }

    function test_LeadingZeroBits_bit247() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 8)), 247, "bit 247");
    }

    function test_LeadingZeroBits_bit248() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 7)), 248, "bit 248");
    }

    function test_LeadingZeroBits_bit249() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 6)), 249, "bit 249");
    }

    function test_LeadingZeroBits_bit250() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 5)), 250, "bit 250");
    }

    function test_LeadingZeroBits_bit251() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 4)), 251, "bit 251");
    }

    function test_LeadingZeroBits_bit252() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 3)), 252, "bit 252");
    }

    function test_LeadingZeroBits_bit253() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 2)), 253, "bit 253");
    }

    function test_LeadingZeroBits_bit254() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 1)), 254, "bit 254");
    }

    function test_LeadingZeroBits_bit255() public {
        assertEq(poc.leadingZeroBits(bytes32(uint256(1) << 0)), 255, "bit 255");
    }

    function test_LeadingZeroBits_allZero() public {
        assertEq(poc.leadingZeroBits(bytes32(0)), 256, "zero word => 256");
    }

    function test_LeadingZeroBits_allOnes() public {
        assertEq(poc.leadingZeroBits(bytes32(type(uint256).max)), 0, "all ones => 0");
    }

    // ==============================================================
    // workFor: deterministic binding of (chainid, contract, miner, nonce)
    // ==============================================================
    function test_WorkFor_deterministic() public {
        assertEq(poc.workFor(address(0x1), 42), poc.workFor(address(0x1), 42));
    }

    function test_WorkFor_variesWithNonce() public {
        assertTrue(poc.workFor(address(0x1), 42) != poc.workFor(address(0x1), 43));
    }

    function test_WorkFor_variesWithMiner() public {
        assertTrue(poc.workFor(address(0x1), 42) != poc.workFor(address(0x2), 42));
    }

    // ==============================================================
    // Staking tier table (deterministic defaults)
    // ==============================================================
    function test_Tier0_lock() public {
        assertEq(config.tierLock(0), 0);
    }

    function test_Tier1_lock() public {
        assertEq(config.tierLock(1), 7 days);
    }

    function test_Tier2_lock() public {
        assertEq(config.tierLock(2), 30 days);
    }

    function test_Tier3_lock() public {
        assertEq(config.tierLock(3), 90 days);
    }

    function test_Tier4_lock() public {
        assertEq(config.tierLock(4), 180 days);
    }

    function test_Tier5_lock() public {
        assertEq(config.tierLock(5), 365 days);
    }

    function test_Tier0_weight() public {
        assertEq(config.tierWeightX1000(0), 1000);
    }

    function test_Tier1_weight() public {
        assertEq(config.tierWeightX1000(1), 5000);
    }

    function test_Tier2_weight() public {
        assertEq(config.tierWeightX1000(2), 10000);
    }

    function test_Tier3_weight() public {
        assertEq(config.tierWeightX1000(3), 20000);
    }

    function test_Tier4_weight() public {
        assertEq(config.tierWeightX1000(4), 30000);
    }

    function test_Tier5_weight() public {
        assertEq(config.tierWeightX1000(5), 40000);
    }

    // ==============================================================
    // Pack size / discount table
    // ==============================================================
    function test_Pack0_size() public {
        assertEq(packs.size(0), 5);
    }

    function test_Pack1_size() public {
        assertEq(packs.size(1), 10);
    }

    function test_Pack2_size() public {
        assertEq(packs.size(2), 25);
    }

    function test_Pack3_size() public {
        assertEq(packs.size(3), 50);
    }

    function test_Pack4_size() public {
        assertEq(packs.size(4), 100);
    }

    function test_Pack0_discount() public {
        assertEq(packs.discountBps(0), 300);
    }

    function test_Pack1_discount() public {
        assertEq(packs.discountBps(1), 600);
    }

    function test_Pack2_discount() public {
        assertEq(packs.discountBps(2), 1200);
    }

    function test_Pack3_discount() public {
        assertEq(packs.discountBps(3), 2000);
    }

    function test_Pack4_discount() public {
        assertEq(packs.discountBps(4), 3000);
    }

    function test_Pack0_price() public {
        assertEq(packs.priceFor(0), ERA_PRICE * 10 - (ERA_PRICE * 10 * 300) / 10000);
    }

    function test_Pack1_price() public {
        assertEq(packs.priceFor(1), ERA_PRICE * 20 - (ERA_PRICE * 20 * 600) / 10000);
    }

    function test_Pack2_price() public {
        assertEq(packs.priceFor(2), ERA_PRICE * 50 - (ERA_PRICE * 50 * 1200) / 10000);
    }

    function test_Pack3_price() public {
        assertEq(packs.priceFor(3), ERA_PRICE * 100 - (ERA_PRICE * 100 * 2000) / 10000);
    }

    function test_Pack4_price() public {
        assertEq(packs.priceFor(4), ERA_PRICE * 200 - (ERA_PRICE * 200 * 3000) / 10000);
    }

}
